package parser

import (
	"errors"

	"github.com/vaastav/columbo_go/events"
)

// Interface that needs to be implemented to parse the log files generated by a given simulator
type Parser interface {
	// Returns the identifier for the parser
	GetIdentifier() int64
	// Returns the name of the parser
	GetName() string
	// Parses an event from the given log line
	// This function is parser implementation specific
	ParseEvent(line string) (*events.Event, error)
}

// Implementation of a base log parser class that can be used by parsers for other simulators
type BaseLogParser struct {
	Identifier int64
	Name       string
}

// Implements [Parser]
func (p *BaseLogParser) GetIdentifier() int64 {
	return p.Identifier
}

// Implements [Parser]
func (p *BaseLogParser) GetName() string {
	return p.Name
}

// Implements [Parser]
func (p *BaseLogParser) ParseEvent(line string) (*events.Event, error) {
	return nil, errors.New("Base Log Parser does not implement ParseEvent")
}
