// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package events

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KEventT-0]
	_ = x[KSimSendSyncT-1]
	_ = x[KSimProcInEventT-2]
	_ = x[KHostInstrT-3]
	_ = x[KHostCallT-4]
	_ = x[KHostMmioImRespPoWT-5]
	_ = x[KHostIdOpT-6]
	_ = x[KHostMmioCRT-7]
	_ = x[KHostMmioCWT-8]
	_ = x[KHostAddrSizeOpT-9]
	_ = x[KHostMmioRT-10]
	_ = x[KHostMmioWT-11]
	_ = x[KHostDmaCT-12]
	_ = x[KHostDmaRT-13]
	_ = x[KHostDmaWT-14]
	_ = x[KHostMsiXT-15]
	_ = x[KHostConfT-16]
	_ = x[KHostClearIntT-17]
	_ = x[KHostPostIntT-18]
	_ = x[KHostPciRWT-19]
	_ = x[KNicMsixT-20]
	_ = x[KNicDmaT-21]
	_ = x[KSetIXT-22]
	_ = x[KNicDmaIT-23]
	_ = x[KNicDmaExT-24]
	_ = x[KNicDmaEnT-25]
	_ = x[KNicDmaCRT-26]
	_ = x[KNicDmaCWT-27]
	_ = x[KNicMmioT-28]
	_ = x[KNicMmioRT-29]
	_ = x[KNicMmioWT-30]
	_ = x[KNicTrxT-31]
	_ = x[KNicTxT-32]
	_ = x[KNicRxT-33]
	_ = x[KNetworKEnqueueT-34]
	_ = x[KNetworKDequeueT-35]
	_ = x[KNetworKDropT-36]
}

const _EventType_name = "KEventTKSimSendSyncTKSimProcInEventTKHostInstrTKHostCallTKHostMmioImRespPoWTKHostIdOpTKHostMmioCRTKHostMmioCWTKHostAddrSizeOpTKHostMmioRTKHostMmioWTKHostDmaCTKHostDmaRTKHostDmaWTKHostMsiXTKHostConfTKHostClearIntTKHostPostIntTKHostPciRWTKNicMsixTKNicDmaTKSetIXTKNicDmaITKNicDmaExTKNicDmaEnTKNicDmaCRTKNicDmaCWTKNicMmioTKNicMmioRTKNicMmioWTKNicTrxTKNicTxTKNicRxTKNetworKEnqueueTKNetworKDequeueTKNetworKDropT"

var _EventType_index = [...]uint16{0, 7, 20, 36, 47, 57, 76, 86, 98, 110, 126, 137, 148, 158, 168, 178, 188, 198, 212, 225, 236, 245, 253, 260, 269, 279, 289, 299, 309, 318, 328, 338, 346, 353, 360, 376, 392, 405}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
